//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieu
    {
        public int maPhieu { get; set; }
        public int maTaiLieu { get; set; }
        public Nullable<int> soLuong { get; set; }
    
        public virtual PhieuMuonTra PhieuMuonTra { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
