//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocGia()
        {
            this.PhieuMuonTra = new HashSet<PhieuMuonTra>();
            this.XyLyVP = new HashSet<XyLyVP>();
        }
    
        public int soThe { get; set; }
        public string tenDocGia { get; set; }
        public string diaChi { get; set; }
        public string dienThoai { get; set; }
        public Nullable<System.DateTime> ngayCap { get; set; }
        public Nullable<System.DateTime> hanSD { get; set; }
        public string nguoiCN { get; set; }
        public Nullable<System.DateTime> ngayCN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuonTra> PhieuMuonTra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XyLyVP> XyLyVP { get; set; }
    }
}
