//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuonTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMuonTra()
        {
            this.ChiTietPhieu = new HashSet<ChiTietPhieu>();
        }
    
        public int maPhieu { get; set; }
        public Nullable<System.DateTime> ngayMuon { get; set; }
        public Nullable<System.DateTime> ngayTra { get; set; }
        public string ghiChu { get; set; }
        public int maNV { get; set; }
        public int soThe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieu> ChiTietPhieu { get; set; }
        public virtual DocGia DocGia { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
