//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class XyLyVP
    {
        public int ID_Phat { get; set; }
        public string liDoVP { get; set; }
        public string htXuLy { get; set; }
        public Nullable<System.DateTime> ngayXL { get; set; }
        public string nguoiXL { get; set; }
        public Nullable<System.DateTime> ngayMoThe { get; set; }
        public int soThe { get; set; }
    
        public virtual DocGia DocGia { get; set; }
    }
}
